#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
emit_latex.py -- xuat model Mace4 ra doan LaTeX dan thang duoc vao bai bao
(thay cho ghi chu \\noteAI trong doc3-structures.tex, prop:order-structure).

Emit the Mace4 model as a LaTeX snippet ready to paste into the paper.

Cach dung / usage:
    python3 emit_latex.py > model.tex
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                ".."))
from ps_model import parse_mace4                              # noqa: E402

# Ten hien thi / display names, indexed by the Mace4 element number.
# Duoc xac dinh boi verify.py: 1 = bottom, 4 = top, 0 = eo.
NAMES = {1: r"\ev", 0: "a", 2: "b", 3: "c", 4: r"\ew"}
ORDER = [1, 0, 2, 3, 4]        # thu tu hien thi / display order


def table(M, fn, title):
    cols = "c|" + "c" * len(ORDER)
    rows = [r"\begin{array}{%s}" % cols]
    rows.append(r"%s & %s \\ \hline"
                % (title, " & ".join(NAMES[j] for j in ORDER)))
    for i in ORDER:
        rows.append(r"%s & %s \\"
                    % (NAMES[i],
                       " & ".join(NAMES[fn(i, j)] for j in ORDER)))
    rows.append(r"\end{array}")
    return "\n".join(rows)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    M = parse_mace4(os.path.join(here, "mace4-outputs", "mace4-output.txt"))
    if M is None:
        print("no model")
        return 1

    print(r"% Sinh tu dong boi emit_latex.py / auto-generated by emit_latex.py")
    print(r"%% Model do Mace4 tim / model found by Mace4, |X| = %d" % M.n)
    print(r"\begin{example}[A non-distributive Polar Semiring]"
          r"\label{ex:nondistributive}")
    print(r"Let $X=\{\ev,a,b,c,\ew\}$ be the five-element modular lattice "
          r"$M_3$, with $\ev$ the least element, $\ew$ the greatest, and "
          r"$a,b,c$ pairwise incomparable. Define the polarity by")
    print(r"\[")
    print(r"  \dstar{\ev}=\ew,\qquad \dstar{\ew}=\ev,\qquad "
          r"\dstar{a}=a,\qquad \dstar{b}=b,\qquad \dstar{c}=c,")
    print(r"\]")
    print(r"and let $\eo:=a$, with the tensor given by the following table "
          r"(the join is the lattice join):")
    print(r"\[")
    print(table(M, M.tensor, r"\otimes"))
    print(r"\]")
    print(r"All eleven axioms of \Cref{def:ps} hold, yet")
    print(r"\[")
    print(r"  a\vee(b\wedge c)=a\vee\ev=a"
          r"\quad\text{whereas}\quad"
          r"(a\vee b)\wedge(a\vee c)=\ew\wedge\ew=\ew .")
    print(r"\]")
    print(r"Hence the induced lattice of a Polar Semiring need not be "
          r"distributive.")
    print(r"\end{example}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
